version: '3.8'

services:
  postgres:
    image: mysql:9.0
    container_name: nbaDbMySql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: asdf
      MYSQL_DATABASE: nbadatabase
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql