version: '3.8'

services:
  postgres:
    image: mysql:9.0
    container_name: nbaDbMySql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_ROOT_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql